version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      ATLAS_URI: mongodb+srv://Micode:micode123@midata-pk9on.mongodb.net/myfavouriteos?retryWrites=true&w=majority
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
