version: "3.8"
services:
  app:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - mongodb+srv://Micode:micode123@midata-pk9on.mongodb.net/myfavouriteos?retryWrites=true&w=majority
    volumes:
      - .:/src/server
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
